name: shop_list
description: project to manage your shop list

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.5
  mask_text_input_formatter: ^2.4.0
  overlay_support: ^2.1.0

  # Architecture
  provider: ^6.0.5
  flutter_bloc: ^8.1.1
  injectable: ^2.1.0
  get_it: ^7.2.0

  # Data
  hive: ^2.2.3
  hive_generator: ^2.0.0
  hive_flutter: ^1.1.0
  drift: ^2.4.2
  sqlite3_flutter_libs: ^0.5.0


  # Utils
  logger: ^1.1.0
  async: ^2.10.0
  equatable: ^2.0.5
  duration: ^3.0.12
  tuple: ^2.0.1
  rxdart: ^0.27.7
  dartz: ^0.10.1
  collection: ^1.16.0
  injectable_generator: ^2.1.3
  freezed_annotation: ^2.2.0
  intl: ^0.17.0
  permission_handler: ^10.2.0
  url_launcher: ^6.1.7
  location: ^4.4.0
  dio_log: ^2.0.4
  path_provider: ^2.0.11
  path: ^1.8.2

dev_dependencies:
  drift_dev: ^2.4.1
  build_runner: ^2.3.3
  freezed: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_intl:
  enabled: true

